name: Deploy action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2

      # delete the existing extract_transform_load.zip file
      - name: Delete existing zip file
        run: |
          rm -rf cloudformation/extract_transform_load.zip
      
      # zip files from database folder, get_connections & lambda_function to folder called extract_transform_load then zip it in the cloud formationfolder
      - name: Zip files
        run: |
          ls
          pwd
          mkdir extract_transform_load
          cp database/get_connections extract_transform_load
          cp database/lambda_function extract_transform_load
          zip -r extract_transform_load.zip extract_transform_load
          mkdir cloudformation
          mv extract_transform_load.zip cloudformation 